export const ACCESS_TOKEN_EXPIRES_IN_MINUTES = 15;
export const ACCESS_TOKEN_EXPIRES_IN_MS =
  ACCESS_TOKEN_EXPIRES_IN_MINUTES * 60 * 1000;

export const REFRESH_TOKEN_EXPIRES_IN_DAYS = 7;
export const REFRESH_TOKEN_EXPIRES_IN_MS =
  REFRESH_TOKEN_EXPIRES_IN_DAYS * 24 * 60 * 60 * 1000;
